# Generated by Django 3.2.14 on 2022-11-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('updationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tblClasses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('className', models.CharField(max_length=100)),
                ('classNameNumeric', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('creationDate', models.DateTimeField()),
                ('updationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tblSubjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField()),
                ('updationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tblSubjectCombination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subjectId', models.IntegerField()),
                ('status', models.IntegerField()),
                ('creationDate', models.DateTimeField()),
                ('updationDate', models.DateTimeField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblclasses')),
            ],
        ),
        migrations.CreateModel(
            name='tblStudents',
            fields=[
                ('studentsId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('studentsName', models.CharField(max_length=100)),
                ('rollId', models.CharField(max_length=100)),
                ('studentsEmail', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=100)),
                ('regDate', models.DateTimeField()),
                ('updationDate', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblclasses')),
            ],
        ),
        migrations.CreateModel(
            name='tblResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField()),
                ('creationDate', models.DateTimeField()),
                ('updationDate', models.DateTimeField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblclasses')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblstudents')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblsubjects')),
            ],
        ),
    ]
